// generated by generate_yaml.py

//
// Enums first
//

const struct YamlIdStr enum_AntennaModes[] = {
  {  ANTENNA_MODE_INTERNAL, "MODE_INTERNAL"  },
  {  ANTENNA_MODE_ASK, "MODE_ASK"  },
  {  ANTENNA_MODE_PER_MODEL, "MODE_PER_MODEL"  },
  {  ANTENNA_MODE_EXTERNAL, "MODE_EXTERNAL"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_ModuleType[] = {
  {  MODULE_TYPE_NONE, "TYPE_NONE"  },
  {  MODULE_TYPE_CROSSFIRE, "TYPE_CROSSFIRE"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_SwitchConfig[] = {
  {  SWITCH_NONE, "NONE"  },
  {  SWITCH_TOGGLE, "TOGGLE"  },
  {  SWITCH_2POS, "2POS"  },
  {  SWITCH_3POS, "3POS"  },
  {  SWITCH_GLOBAL, "GLOBAL"  },
  {  SWITCH_none, "none"  },
  {  SWITCH_toggle, "toggle"  },
  {  SWITCH_2pos, "2pos"  },
  {  SWITCH_3pos, "3pos"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_fsStartPositionType[] = {
  {  FS_START_OFF, "START_OFF"  },
  {  FS_START_ON, "START_ON"  },
  {  FS_START_PREVIOUS, "START_PREVIOUS"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_booleanEnum[] = {
  {  BOOL_OFF, "OFF"  },
  {  BOOL_ON, "ON"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_SwitchSources[] = {
  {  SWSRC_NONE, "NONE"  },
  {  SWSRC_ON, "ON"  },
  {  SWSRC_ONE, "ONE"  },
  {  SWSRC_TELEMETRY_STREAMING, "TELEMETRY_STREAMING"  },
  {  SWSRC_RADIO_ACTIVITY, "RADIO_ACTIVITY"  },
  {  SWSRC_OFF, "OFF"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_TimerModes[] = {
  {  TMRMODE_OFF, "OFF"  },
  {  TMRMODE_ON, "ON"  },
  {  TMRMODE_START, "START"  },
  {  TMRMODE_THR, "THR"  },
  {  TMRMODE_THR_REL, "THR_REL"  },
  {  TMRMODE_THR_START, "THR_START"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_MixerMultiplex[] = {
  {  MLTPX_ADD, "ADD"  },
  {  MLTPX_MUL, "MUL"  },
  {  MLTPX_REPL, "REPL"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_MixSources[] = {
  {  MIXSRC_NONE, "NONE"  },
  {  MIXSRC_SPACEMOUSE_A, "SPACEMOUSE_A"  },
  {  MIXSRC_SPACEMOUSE_B, "SPACEMOUSE_B"  },
  {  MIXSRC_SPACEMOUSE_C, "SPACEMOUSE_C"  },
  {  MIXSRC_SPACEMOUSE_D, "SPACEMOUSE_D"  },
  {  MIXSRC_SPACEMOUSE_E, "SPACEMOUSE_E"  },
  {  MIXSRC_SPACEMOUSE_F, "SPACEMOUSE_F"  },
  {  MIXSRC_MIN, "MIN"  },
  {  MIXSRC_MAX, "MAX"  },
  {  MIXSRC_TX_VOLTAGE, "TX_VOLTAGE"  },
  {  MIXSRC_TX_TIME, "TX_TIME"  },
  {  MIXSRC_TX_GPS, "TX_GPS"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_PotsWarnMode[] = {
  {  POTS_WARN_OFF, "WARN_OFF"  },
  {  POTS_WARN_MANUAL, "WARN_MANUAL"  },
  {  POTS_WARN_AUTO, "WARN_AUTO"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_ModelOverridableEnable[] = {
  {  OVERRIDE_GLOBAL, "GLOBAL"  },
  {  OVERRIDE_OFF, "OFF"  },
  {  OVERRIDE_ON, "ON"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_TelemetrySensorFormula[] = {
  {  TELEM_FORMULA_ADD, "FORMULA_ADD"  },
  {  TELEM_FORMULA_AVERAGE, "FORMULA_AVERAGE"  },
  {  TELEM_FORMULA_MIN, "FORMULA_MIN"  },
  {  TELEM_FORMULA_MAX, "FORMULA_MAX"  },
  {  TELEM_FORMULA_MULTIPLY, "FORMULA_MULTIPLY"  },
  {  TELEM_FORMULA_TOTALIZE, "FORMULA_TOTALIZE"  },
  {  TELEM_FORMULA_CELL, "FORMULA_CELL"  },
  {  TELEM_FORMULA_CONSUMPTION, "FORMULA_CONSUMPTION"  },
  {  TELEM_FORMULA_DIST, "FORMULA_DIST"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_TelemetrySensorType[] = {
  {  TELEM_TYPE_CUSTOM, "TYPE_CUSTOM"  },
  {  TELEM_TYPE_CALCULATED, "TYPE_CALCULATED"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_USBJoystickIfMode[] = {
  {  USBJOYS_JOYSTICK, "JOYSTICK"  },
  {  USBJOYS_GAMEPAD, "GAMEPAD"  },
  {  USBJOYS_MULTIAXIS, "MULTIAXIS"  },
  {  0, NULL  }
};
const struct YamlIdStr enum_USBJoystickCh[] = {
  {  USBJOYS_CH_NONE, "CH_NONE"  },
  {  USBJOYS_CH_BUTTON, "CH_BUTTON"  },
  {  USBJOYS_CH_AXIS, "CH_AXIS"  },
  {  USBJOYS_CH_SIM, "CH_SIM"  },
  {  0, NULL  }
};

//
// Structs last
//

static const struct YamlNode struct_RGBLedColor[] = {
  YAML_UNSIGNED( "r", 8 ),
  YAML_UNSIGNED( "g", 8 ),
  YAML_UNSIGNED( "b", 8 ),
  YAML_END
};
static const struct YamlNode struct_unsigned_8[] = {
  YAML_IDX,
  YAML_UNSIGNED( "val", 8 ),
  YAML_END
};
static const struct YamlNode struct_ModelHeader[] = {
  YAML_STRING("name", 15),
  YAML_ARRAY("modelId", 8, 2, struct_unsigned_8, NULL),
  YAML_STRING("bitmap", 14),
  YAML_STRING("labels", 100),
  YAML_END
};
static const struct YamlNode struct_TimerData[] = {
  YAML_IDX,
  YAML_UNSIGNED( "start", 22 ),
  YAML_SIGNED_CUST( "swtch", 10, r_swtchSrc, w_swtchSrc ),
  YAML_SIGNED( "value", 22 ),
  YAML_ENUM("mode", 3, enum_TimerModes, NULL),
  YAML_UNSIGNED( "countdownBeep", 2 ),
  YAML_UNSIGNED( "minuteBeep", 1 ),
  YAML_UNSIGNED( "persistent", 2 ),
  YAML_SIGNED( "countdownStart", 2 ),
  YAML_UNSIGNED( "showElapsed", 1 ),
  YAML_UNSIGNED( "extraHaptic", 1 ),
  YAML_PADDING( 6 ),
  YAML_STRING("name", 8),
  YAML_END
};
static const struct YamlNode struct_CurveRef[] = {
  YAML_UNSIGNED( "type", 5 ),
  YAML_SIGNED( "value", 11 ),
  YAML_END
};
static const struct YamlNode struct_MixData[] = {
  YAML_UNSIGNED( "destCh", 5 ),
  YAML_SIGNED_CUST( "srcRaw", 10, r_mixSrcRawEx, w_mixSrcRawEx ),
  YAML_PADDING( 1 ),
  YAML_UNSIGNED( "mixWarn", 2 ),
  YAML_ENUM("mltpx", 2, enum_MixerMultiplex, NULL),
  YAML_UNSIGNED( "delayPrec", 1 ),
  YAML_UNSIGNED( "speedPrec", 1 ),
  YAML_PADDING( 2 ),
  YAML_SIGNED( "weight", 11 ),
  YAML_SIGNED( "offset", 11 ),
  YAML_SIGNED_CUST( "swtch", 10, r_swtchSrc, w_swtchSrc ),
  YAML_STRUCT("curve", 16, struct_CurveRef, NULL),
  YAML_UNSIGNED( "delayUp", 8 ),
  YAML_UNSIGNED( "delayDown", 8 ),
  YAML_UNSIGNED( "speedUp", 8 ),
  YAML_UNSIGNED( "speedDown", 8 ),
  YAML_STRING("name", 6),
  YAML_END
};
static const struct YamlNode struct_LimitData[] = {
  YAML_IDX,
  YAML_SIGNED( "min", 11 ),
  YAML_SIGNED( "max", 11 ),
  YAML_SIGNED( "ppmCenter", 10 ),
  YAML_SIGNED( "offset", 11 ),
  YAML_UNSIGNED( "symetrical", 1 ),
  YAML_UNSIGNED( "revert", 1 ),
  YAML_PADDING( 3 ),
  YAML_SIGNED( "curve", 8 ),
  YAML_STRING("name", 6),
  YAML_END
};
static const struct YamlNode struct_ExpoData[] = {
  YAML_UNSIGNED( "mode", 2 ),
  YAML_UNSIGNED( "scale", 14 ),
  YAML_PADDING( 6 ),
  YAML_SIGNED_CUST( "srcRaw", 10, r_mixSrcRawEx, w_mixSrcRawEx ),
  YAML_SIGNED( "weight", 11 ),
  YAML_SIGNED( "offset", 11 ),
  YAML_SIGNED_CUST( "swtch", 10, r_swtchSrc, w_swtchSrc ),
  YAML_STRUCT("curve", 16, struct_CurveRef, NULL),
  YAML_UNSIGNED( "chn", 5 ),
  YAML_PADDING( 3 ),
  YAML_STRING("name", 6),
  YAML_END
};
static const struct YamlNode struct_CurveHeader[] = {
  YAML_IDX,
  YAML_UNSIGNED( "type", 1 ),
  YAML_UNSIGNED( "smooth", 1 ),
  YAML_SIGNED( "points", 6 ),
  YAML_STRING("name", 3),
  YAML_END
};
static const struct YamlNode struct_signed_8[] = {
  YAML_IDX,
  YAML_SIGNED( "val", 8 ),
  YAML_END
};
static const struct YamlNode struct_VarioData[] = {
  YAML_UNSIGNED_CUST( "source", 7, r_tele_sensor, w_tele_sensor ),
  YAML_UNSIGNED( "centerSilent", 1 ),
  YAML_SIGNED( "centerMax", 8 ),
  YAML_SIGNED( "centerMin", 8 ),
  YAML_SIGNED( "min", 8 ),
  YAML_SIGNED( "max", 8 ),
  YAML_END
};
static const struct YamlNode struct_RFAlarmData[] = {
  YAML_SIGNED( "warning", 8 ),
  YAML_SIGNED( "critical", 8 ),
  YAML_END
};
static const struct YamlNode struct_anonymous_1[] = {
  YAML_UNSIGNED( "telemetryBaudrate", 3 ),
  YAML_UNSIGNED( "crsfArmingMode", 1 ),
  YAML_PADDING( 4 ),
  YAML_SIGNED_CUST( "crsfArmingTrigger", 10, r_swtchSrc, w_swtchSrc ),
  YAML_SIGNED( "spare3", 6 ),
  YAML_END
};
static const struct YamlNode union_anonymous_0_elmts[] = {
  YAML_STRUCT("crsf", 24, struct_anonymous_1, NULL),
  YAML_END
};
static const struct YamlNode struct_ModuleData[] = {
  YAML_IDX,
  YAML_UNSIGNED_CUST( "type", 6, r_moduleType, w_moduleType ),
  YAML_ENUM("antennaMode", 2, enum_AntennaModes, NULL),
  YAML_UNSIGNED( "channelsStart", 8 ),
  YAML_SIGNED_CUST( "channelsCount", 8, r_channelsCount, w_channelsCount ),
  YAML_UNION("mod", 24, union_anonymous_0_elmts, select_mod_type),
  YAML_END
};
static const struct YamlNode union_ScriptDataInput_elmts[] = {
  YAML_SIGNED( "value", 16 ),
  YAML_UNSIGNED_CUST( "source", 16, r_mixSrcRaw, w_mixSrcRaw ),
  YAML_END
};
static const struct YamlNode union_ScriptDataInput[] = {
  YAML_IDX,
  YAML_UNION("u", 16, union_ScriptDataInput_elmts, select_script_input),
  YAML_END
};
static const struct YamlNode struct_ScriptData[] = {
  YAML_IDX,
  YAML_STRING("file", 6),
  YAML_STRING("name", 6),
  YAML_ARRAY("inputs", 16, 6, union_ScriptDataInput, NULL),
  YAML_END
};
static const struct YamlNode struct_string_32[] = {
  YAML_IDX,
  YAML_STRING("val", 4),
  YAML_END
};
static const struct YamlNode union_anonymous_2_elmts[] = {
  YAML_UNSIGNED( "id", 16 ),
  YAML_UNSIGNED( "persistentValue", 16 ),
  YAML_END
};
static const struct YamlNode union_anonymous_3_elmts[] = {
  YAML_UNSIGNED( "instance", 8 ),
  YAML_ENUM("formula", 8, enum_TelemetrySensorFormula, NULL),
  YAML_END
};
static const struct YamlNode struct_anonymous_5[] = {
  YAML_UNSIGNED( "ratio", 16 ),
  YAML_SIGNED( "offset", 16 ),
  YAML_END
};
static const struct YamlNode struct_anonymous_6[] = {
  YAML_UNSIGNED( "source", 8 ),
  YAML_UNSIGNED( "index", 8 ),
  YAML_PADDING( 16 ),
  YAML_END
};
static const struct YamlNode struct_anonymous_7[] = {
  YAML_ARRAY("sources", 8, 4, struct_signed_8, NULL),
  YAML_END
};
static const struct YamlNode struct_anonymous_8[] = {
  YAML_UNSIGNED( "source", 8 ),
  YAML_PADDING( 24 ),
  YAML_END
};
static const struct YamlNode struct_anonymous_9[] = {
  YAML_UNSIGNED( "gps", 8 ),
  YAML_UNSIGNED( "alt", 8 ),
  YAML_PADDING( 16 ),
  YAML_END
};
static const struct YamlNode union_anonymous_4_elmts[] = {
  YAML_STRUCT("custom", 32, struct_anonymous_5, NULL),
  YAML_STRUCT("cell", 32, struct_anonymous_6, NULL),
  YAML_STRUCT("calc", 32, struct_anonymous_7, NULL),
  YAML_STRUCT("consumption", 32, struct_anonymous_8, NULL),
  YAML_STRUCT("dist", 32, struct_anonymous_9, NULL),
  YAML_UNSIGNED( "param", 32 ),
  YAML_END
};
static const struct YamlNode struct_TelemetrySensor[] = {
  YAML_IDX,
  YAML_UNION("id1", 16, union_anonymous_2_elmts, select_id1),
  YAML_UNION("id2", 8, union_anonymous_3_elmts, select_id2),
  YAML_STRING("label", 4),
  YAML_UNSIGNED( "subId", 8 ),
  YAML_ENUM("type", 1, enum_TelemetrySensorType, NULL),
  YAML_PADDING( 1 ),
  YAML_UNSIGNED( "unit", 6 ),
  YAML_UNSIGNED( "prec", 2 ),
  YAML_UNSIGNED( "autoOffset", 1 ),
  YAML_UNSIGNED( "filter", 1 ),
  YAML_UNSIGNED( "logs", 1 ),
  YAML_UNSIGNED( "persistent", 1 ),
  YAML_UNSIGNED( "onlyPositive", 1 ),
  YAML_PADDING( 1 ),
  YAML_UNION("cfg", 32, union_anonymous_4_elmts, select_sensor_cfg),
  YAML_END
};
static const struct YamlNode union_WidgetOptionValue_elmts[] = {
  YAML_CUSTOM("unsignedValue",r_wov_unsigned,w_wov_unsigned),
  YAML_CUSTOM("signedValue",r_wov_signed,w_wov_signed),
  YAML_CUSTOM("boolValue",r_wov_unsigned,w_wov_unsigned),
  YAML_CUSTOM("stringValue",r_wov_string,w_wov_string),
  YAML_CUSTOM("source",r_wov_source,w_wov_source),
  YAML_CUSTOM("color",r_wov_color,w_wov_color),
  YAML_END
};
static const struct YamlNode struct_WidgetOptionValueTyped[] = {
  YAML_IDX,
  YAML_CUSTOM("type",r_wov_type,w_wov_type),
  YAML_UNION("value", 0, union_WidgetOptionValue_elmts, select_wov),
  YAML_END
};
static const struct YamlNode struct_WidgetPersistentData[] = {
  YAML_ARRAY("options", 0, 50, struct_WidgetOptionValueTyped, widget_option_is_active),
  YAML_END
};
static const struct YamlNode struct_ZonePersistentData[] = {
  YAML_IDX,
  YAML_CUSTOM("widgetName",r_widget_name,w_widget_name),
  YAML_STRUCT("widgetData", 0, struct_WidgetPersistentData, isAlwaysActive),
  YAML_END
};
static const struct YamlNode union_LayoutOptionValue_elmts[] = {
  YAML_CUSTOM("unsignedValue",r_lov_unsigned,w_lov_unsigned),
  YAML_CUSTOM("boolValue",r_lov_unsigned,w_lov_unsigned),
  YAML_CUSTOM("color",r_lov_color,w_lov_color),
  YAML_END
};
static const struct YamlNode struct_LayoutOptionValueTyped[] = {
  YAML_IDX,
  YAML_CUSTOM("type",r_lov_type,w_lov_type),
  YAML_UNION("value", 0, union_LayoutOptionValue_elmts, select_lov),
  YAML_END
};
static const struct YamlNode struct_LayoutPersistentData[] = {
  YAML_ARRAY("zones", 0, 10, struct_ZonePersistentData, widget_is_active),
  YAML_ARRAY("options", 0, 10, struct_LayoutOptionValueTyped, layout_option_is_active),
  YAML_END
};
static const struct YamlNode struct_CustomScreenData[] = {
  YAML_IDX,
  YAML_CUSTOM("LayoutId",r_screen_id,w_screen_id),
  YAML_STRUCT("layoutData", 0, struct_LayoutPersistentData, isAlwaysActive),
  YAML_END
};
static const struct YamlNode struct_TopBarPersistentData[] = {
  YAML_ARRAY("zones", 0, 5, struct_ZonePersistentData, widget_is_active),
  YAML_END
};
static const struct YamlNode struct_customSwitch[] = {
  YAML_IDX_CUST("sw",cfs_idx_read,cfs_idx_write),
  YAML_STRING("name", 3),
  YAML_ENUM("type", 3, enum_SwitchConfig, NULL),
  YAML_UNSIGNED( "group", 2 ),
  YAML_ENUM("start", 2, enum_fsStartPositionType, NULL),
  YAML_UNSIGNED( "state", 1 ),
  YAML_ENUM("onColorLuaOverride", 1, enum_booleanEnum, NULL),
  YAML_ENUM("offColorLuaOverride", 1, enum_booleanEnum, NULL),
  YAML_PADDING( 6 ),
  YAML_STRUCT("onColor", 24, struct_RGBLedColor, isAlwaysActive),
  YAML_STRUCT("offColor", 24, struct_RGBLedColor, isAlwaysActive),
  YAML_END
};
static const struct YamlNode struct_USBJoystickChData[] = {
  YAML_IDX,
  YAML_ENUM("mode", 3, enum_USBJoystickCh, NULL),
  YAML_UNSIGNED( "inversion", 1 ),
  YAML_UNSIGNED( "param", 4 ),
  YAML_UNSIGNED( "btn_num", 5 ),
  YAML_UNSIGNED( "switch_npos", 3 ),
  YAML_END
};
static const struct YamlNode struct_ModelData[] = {
  YAML_CUSTOM("semver",nullptr,w_semver),
  YAML_STRUCT("header", 1048, struct_ModelHeader, NULL),
  YAML_ARRAY("timers", 136, 3, struct_TimerData, NULL),
  YAML_UNSIGNED( "telemetryProtocol", 3 ),
  YAML_PADDING( 1 ),
  YAML_PADDING( 1 ),
  YAML_PADDING( 2 ),
  YAML_UNSIGNED( "ignoreSensorIds", 1 ),
  YAML_PADDING( 3 ),
  YAML_UNSIGNED( "disableThrottleWarning", 1 ),
  YAML_UNSIGNED( "displayChecklist", 1 ),
  YAML_UNSIGNED( "extendedLimits", 1 ),
  YAML_PADDING( 1 ),
  YAML_UNSIGNED( "throttleReversed", 1 ),
  YAML_UNSIGNED( "enableCustomThrottleWarning", 1 ),
  YAML_UNSIGNED( "disableTelemetryWarning", 1 ),
  YAML_UNSIGNED( "showInstanceIds", 1 ),
  YAML_UNSIGNED( "checklistInteractive", 1 ),
  YAML_PADDING( 4 ),
  YAML_SIGNED( "customThrottleWarningPosition", 8 ),
  YAML_UNSIGNED( "beepANACenter", 16 ),
  YAML_ARRAY("mixData", 152, 64, struct_MixData, NULL),
  YAML_ARRAY("limitData", 104, 32, struct_LimitData, NULL),
  YAML_ARRAY("expoData", 136, 64, struct_ExpoData, NULL),
  YAML_ARRAY("curves", 32, 32, struct_CurveHeader, NULL),
  YAML_ARRAY("points", 8, 512, struct_signed_8, NULL),
  YAML_UNSIGNED_CUST( "thrTraceSrc", 8, r_thrSrc, w_thrSrc ),
  YAML_CUSTOM("switchWarningState",r_swtchWarn,nullptr),
  YAML_ARRAY("switchWarning", 2, 32, struct_swtchWarn, nullptr),
  YAML_STRUCT("varioData", 40, struct_VarioData, NULL),
  YAML_STRUCT("rfAlarms", 16, struct_RFAlarmData, NULL),
  YAML_PADDING( 3 ),
  YAML_ENUM("potsWarnMode", 2, enum_PotsWarnMode, NULL),
  YAML_ENUM("jitterFilter", 2, enum_ModelOverridableEnable, NULL),
  YAML_PADDING( 1 ),
  YAML_ARRAY("moduleData", 48, 2, struct_ModuleData, NULL),
  YAML_ARRAY("scriptsData", 192, 9, struct_ScriptData, NULL),
  YAML_ARRAY("inputNames", 32, 32, struct_string_32, NULL),
  YAML_UNSIGNED( "potsWarnEnabled", 16 ),
  YAML_ARRAY("potsWarnPosition", 8, 16, struct_signed_8, NULL),
  YAML_ARRAY("telemetrySensors", 112, 99, struct_TelemetrySensor, NULL),
  YAML_ARRAY("screenData", 0, 10, struct_CustomScreenData, screen_is_active),
  YAML_STRUCT("topbarData", 0, struct_TopBarPersistentData, isAlwaysActive),
  YAML_ARRAY("topbarWidgetWidth", 8, 5, struct_unsigned_8, NULL),
  YAML_UNSIGNED( "view", 8 ),
  YAML_CUSTOM("functionSwitchConfig",r_functionSwitchConfig,nullptr),
  YAML_CUSTOM("functionSwitchGroup",r_functionSwitchGroup,nullptr),
  YAML_CUSTOM("functionSwitchStartConfig",r_functionSwitchStartConfig,nullptr),
  YAML_CUSTOM("functionSwitchLogicalState",r_functionSwitchLogicalState,nullptr),
  YAML_ARRAY("switchNames", 0, NUM_FUNCTIONS_SWITCHES, struct_cfsNameConfig, nullptr),
  YAML_ARRAY("functionSwitchLedONColor", 0, NUM_FUNCTIONS_SWITCHES, struct_cfsOnColorConfig, nullptr),
  YAML_ARRAY("functionSwitchLedOFFColor", 0, NUM_FUNCTIONS_SWITCHES, struct_cfsOffColorConfig, nullptr),
  YAML_ARRAY("customSwitches", 88, 6, struct_customSwitch, isAlwaysActive),
  YAML_ARRAY("cfsGroupOn", 1, 8, struct_cfsGroupOn, cfsGroupIsActive),
  YAML_UNSIGNED( "usbJoystickExtMode", 1 ),
  YAML_ENUM("usbJoystickIfMode", 3, enum_USBJoystickIfMode, NULL),
  YAML_UNSIGNED( "usbJoystickCircularCut", 4 ),
  YAML_ARRAY("usbJoystickCh", 16, 26, struct_USBJoystickChData, NULL),
  YAML_ENUM("radioThemesDisabled", 2, enum_ModelOverridableEnable, NULL),
  YAML_PADDING( 2 ),
  YAML_PADDING( 2 ),
  YAML_ENUM("modelCurvesDisabled", 2, enum_ModelOverridableEnable, NULL),
  YAML_PADDING( 2 ),
  YAML_PADDING( 2 ),
  YAML_ENUM("modelCustomScriptsDisabled", 2, enum_ModelOverridableEnable, NULL),
  YAML_ENUM("modelTelemetryDisabled", 2, enum_ModelOverridableEnable, NULL),
  YAML_END
};
static const struct YamlNode struct_PartialModel[] = {
  YAML_CUSTOM("semver",nullptr,w_semver),
  YAML_STRUCT("header", 1048, struct_ModelHeader, NULL),
  YAML_ARRAY("moduleData", 48, 2, struct_ModuleData, NULL),
  YAML_END
};

#define MAX_MODELDATA_PARTIALMODEL_STR_LEN 29

static const struct YamlNode __ModelData_root_node = YAML_ROOT( struct_ModelData );

const YamlNode* get_modeldata_nodes()
{
   return &__ModelData_root_node;
}
static const struct YamlNode __PartialModel_root_node = YAML_ROOT( struct_PartialModel );

const YamlNode* get_partialmodel_nodes()
{
   return &__PartialModel_root_node;
}
